services:
  chroma:
    build:
      context: ./services/chroma
    container_name: chroma
    env_file:
      - .env
    environment:
      - CHROMA_PERSIST_DIRECTORY=${CHROMA_PERSIST_DIRECTORY}
      - CSV_FILE_PATH=${CSV_FILE_PATH}
    ports:
      - "${CHROMA_PORT}:8000"
    volumes:
      - chroma_data:/app/llm_service/chroma_vector_store
      - ./services/chroma:/app


  sec_rag:
    build:
      context: ./services/sec_rag
    container_name: sec_rag_api
    env_file:
      - .env
    ports:
      - "${LLM_PORT}:8000"
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - CHROMA_HOST=${CHROMA_HOST}
      - CHROMA_PORT=${CHROMA_PORT}
    depends_on:
      - chroma

  base_llm:
    build:
      context: ./services/base_llm
    container_name: base_llm_api
    env_file:
      - .env
    ports:
      - "${BASE_LLM_PORT}:8002"
    environment:
      - OLLAMA_HOST=${OLLAMA_HOST}
      - OLLAMA_PORT=${OLLAMA_PORT}
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    env_file:
      - .env
    environment:
      - OLLAMA_DATA=/root/.ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "${OLLAMA_PORT}:11435"

volumes:
  chroma_data:
  ollama_data:

networks:
  sec_rag_network:
    driver: bridge
